apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: TestApplicationBackstage
  annotations:
    confluence/page: TestApplication Backstage
    createdBy: admin
    createdFrom: Created from Backstage
    createdAt: Wed Jun 19 2024 17:04:54 GMT+0530 (India Standard Time)
    updatedFrom: ''
    lastUpdatedAt: ''
spec:
  type: service
  owner: guest
  lifecycle: experimental
  version: TestApplication Backstage
  projectInfo:
    projectName: TestApplication Backstage
    moduleName: ''
    informationAuthor: ''
    modality: ''
    bodyParts: ''
    processingPurpose: ''
    protocol: ''
    algorithmType: ''
    packageType: ''
    supportedOs: Windows
    sourceCodeLanguage: ''
    developmentStatus: DEVELOPMENT
    linkToProject: ''
  applicationInfo:
    linkAPI: ''
    inputImages: ''
    inputValues: ''
    outputImages: ''
    outputValues: ''
    limitations: ''
    algorithmDevelopmentCompany: ''
  productization:
    productizedApplication: ''
    function: ''
    productizedOwner: ''
    releaseNotes: ''
    knowIssues: ''
  evaluationInformation:
    evaluationResults: ''
    evaluationType: ''
    clinicalData: ''
  algorithmInformation:
    developmentPurpose: ''
    developmentStatus: POC
    algorithmDevelopmentCompany: ''
    personinCharge: ''
    collaborativeResearchPartner: ''
    existenceofExternalIP: ''
  technologyInformationforCMRE:
    fundingProject: ''
    group: IMAGE ANALYSIS
    TRL: A-NICE
    projectStatus: ACTIVE
